### ISSUE TITLE
Cant pick last ascension perk

### ISSUE THREAD

**Issue by kingwolf1989** [OriginalTrinity/More-Ascension-Perk-Slots#9] opened 2022-03-06 19:02 UTC
When i am attempting to pick the last tree, game just straight up crashes.

**Comment by OriginalTrinity** [comment] 2022-03-07 06:10
Duplicate of #4 

If you think this is a new issue, please provide the following:

- Your error log
- Your Stellaris Version
- The **exact** load order of any other mods you're using

**Closed by OriginalTrinity** 2022-03-07 06:10 UTC
Labels: Compatibility Issue, Load Order related
